/*
 * This file is generated by jOOQ.
 */
package models.tables


import java.util.function.Function

import models.Public
import models.keys.TODO_PKEY
import models.tables.records.TodoRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Todo(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TodoRecord>?,
    aliased: Table<TodoRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TodoRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.todo</code>
         */
        val TODO: Todo = Todo()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TodoRecord> = TodoRecord::class.java

    /**
     * The column <code>public.todo.user</code>.
     */
    val USER: TableField<TodoRecord, Long?> = createField(DSL.name("user"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.todo.content</code>.
     */
    val CONTENT: TableField<TodoRecord, Array<String?>?> = createField(DSL.name("content"), SQLDataType.VARCHAR(2000).getArrayDataType(), this, "")

    private constructor(alias: Name, aliased: Table<TodoRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TodoRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.todo</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.todo</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.todo</code> table reference
     */
    constructor(): this(DSL.name("todo"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TodoRecord>): this(Internal.createPathAlias(child, key), child, key, TODO, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<TodoRecord> = TODO_PKEY
    override fun `as`(alias: String): Todo = Todo(DSL.name(alias), this)
    override fun `as`(alias: Name): Todo = Todo(alias, this)
    override fun `as`(alias: Table<*>): Todo = Todo(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Todo = Todo(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Todo = Todo(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Todo = Todo(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Long?, Array<String?>?> = super.fieldsRow() as Row2<Long?, Array<String?>?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Array<String?>?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Array<String?>?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
