/*
 * This file is generated by jOOQ.
 */
package models.keys


import models.tables.Todo
import models.tables.records.TodoRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val TODO_PKEY: UniqueKey<TodoRecord> = Internal.createUniqueKey(Todo.TODO, DSL.name("todo_pkey"), arrayOf(Todo.TODO.USER), true)
